#!/bin/sh
# start sway on ArchLinux
# probably will work on BSD too

#https://community.kde.org/Kdenlive/Development#Wayland
export QT_QPA_PLATFORM=wayland-egl
export SDL_VIDEODRIVER=wayland
#https://wiki.archlinux.org/index.php/Wayland
export CLUTTER_BACKEND=wayland
export MOZ_ENABLE_WAYLAND=1
export LIBGL_ALWAYS_SOFTWARE=1
export XDG_SESSION_TYPE=wayland
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1

export XKB_DEFAULT_LAYOUT=us
exec dbus-run-session sway
